version: 0.2

#env:
#  variables:
#    JAVA_HOME: "/usr/lib/jvm/java-11-openjdk-amd64"
phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - echo Build started on `date`
      - mvn --version
      - ls
      - mvn surefire-report:report
reports:
  SurefireReports:
    files:
      - '**/*'
    base-directory: 'target/surefire-reports' # Location of the reports