version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - mvn verify
  post_build:
    commands:
      - mvn test -Dtest=CucumberRunnerPostDeploy -Dcucumber.plugin="junit:target/cucumber-reports/postdeploy/cucumber-results.xml, usage:target/cucumber-reports/postdeploy/cucumber-usage.json"
    finally:
      - find target/surefire-reports/ -name "*Cucumber*" -delete
      - find target/failsafe-reports/ -name "*Cucumber*" -delete
reports:
  BuildTimeTests:
    files:
      - 'target/surefire-reports/TEST*.xml'
      - 'target/failsafe-reports/TEST*.xml'
      - 'target/cucumber-reports/buildtime/cucumber-results.xml'
  Integration:
    files:
      - 'target/cucumber-reports/postdeploy/cucumber-results.xml'
  jacoco-report:
    files:
      - 'target/site/jacoco/jacoco.xml'
    file-format: 'JACOCOXML'
cache:
  paths:
    - '/root/.m2/**/*'